name: Drone Tests

on:
  pull_request:
    branches:
      - dev
      - release/testing
      - release/competition
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          cd src/autonomy
          pytest --cov
