name: flake8 Lint

on: [ push, pull_request ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-bugbear flake8-warnings flake8-class-attributes-order flake8-commas flake8-comprehensions flake8-literal flake8-multiline-containers flake8-newspaper-style flake8-quotes flake8-return flake8-functions flake8-pytest-style flake8-pytest dlint"